<?php
$lang = [
    'en' => [
        'welcome' => 'Marketplace Nearby',
        'secure_btn' => 'Secure with Escrow',
        'chat_btn' => 'Chat with Seller',
        'price' => 'R',
        'success_msg' => 'Item secured in Escrow!',
        'login_title' => 'Login',
        'username' => 'Username',
        'password' => 'Password',
        'signin_btn' => 'Sign In',
        'need_account' => 'Need an account? Register here',
        'nav_login' => 'Login',
        'nav_register' => 'Register',
        'nav_sell' => '+ Sell Something',
        'nav_logout' => 'Logout',
        'location' => 'Location',
        'available' => 'Still available?',
        'trade_complete' => 'Trade Successful!',
        'status_sold' => 'The product status has been updated to SOLD.',
        'back_market' => 'Back to Market',
        'err_pass' => 'Incorrect Password',
        'err_user' => 'User not found',
        'phone_label' => 'Phone Number (for WhatsApp)',
        'admin_label' => 'Admin Secret Key (Optional)',
        'admin_note' => 'Only for authorized staff.',
    ],

    'zu' => [
        'welcome' => 'Imakethe Eduze Nawe',
        'secure_btn' => 'Vikela nge-Escrow',
        'chat_btn' => 'Xoxa nomdayisi',
        'price' => 'R',
        'success_msg' => 'Isitemu sivikelekile e-Escrow!',
        'login_title' => 'Ngena',
        'username' => 'Igama lomsebenzisi',
        'password' => 'Inombolo yemfihlo',
        'signin_btn' => 'Ngena khona manje',
        'need_account' => 'Awunayo i-akhawunti? Bhalisa lapha',
        'nav_login' => 'Ngena',
        'nav_register' => 'Bhalisa',
        'nav_sell' => '+ Dayisa Okuthile',
        'nav_logout' => 'Phuma',
        'location' => 'Indawo',
        'available' => 'Ikhona namanje?',
        'trade_complete' => 'Uhwebo luphumelele!',
        'status_sold' => 'Isimo somkhiqizo sibuyekeziwe saba ngu-KUDAYISIWE.',
        'back_market' => 'Buyela Emakethe',
        'err_pass' => 'Inombolo yemfihlo ayilungile',
        'err_user' => 'Umsebenzisi akatholakali',
        'phone_label' => 'Inombolo yocingo (ye-WhatsApp)',
        'admin_label' => 'Ikhodi yemfihlo yomlawuli (Ongakukhetha)',
        'admin_note' => 'Okwabasebenzi abagunyaziwe kuphela.',
    ],

    'xh' => [
        'welcome' => 'Indawo yoThengiso ekufutshane',
        'secure_btn' => 'Khusela nge-Escrow',
        'chat_btn' => 'Ncokola nomthengisi',
        'price' => 'R',
        'success_msg' => 'Impahla ikhuselekile kwi-Escrow!',
        'login_title' => 'Ngena',
        'username' => 'Igama lomsebenzisi',
        'password' => 'Inombolo yokungena',
        'signin_btn' => 'Ngena ngoku',
        'need_account' => 'Awunayo i-akhawunti? Bhalisa apha',
        'nav_login' => 'Ngena',
        'nav_register' => 'Bhalisa',
        'nav_sell' => '+ Thengisa Into',
        'nav_logout' => 'Phuma',
        'location' => 'Indawo',
        'available' => 'Isafumaneka?',
        'trade_complete' => 'Urwebo luphumelele!',
        'status_sold' => 'Ubume bemveliso buhlaziyiwe baze ba-THENGISWA.',
        'back_market' => 'Buyela kwindawo yoThengiso',
        'err_pass' => 'Inombolo yokungena ayichanekanga',
        'err_user' => 'Umsebenzisi akafumaneki',
        'phone_label' => 'Inombolo yemfoni (ye-WhatsApp)',
        'admin_label' => 'Isitshixo se-Admin (Ungakhetha)',
        'admin_note' => 'Yabasebenzi abagunyazisiweyo kuphela.',
    ],
];    


$current_lang = $_SESSION['lang'] ?? 'en';
$words = $lang[$current_lang];
?>